default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("DATABASE_POOL_SIZE", 5) %>
  url: <%= ENV["DATABASE_URL"] %>

development:
  <<: *default
  database: cocopay_development

test:
  <<: *default
  database: cocopay_test
  url: <%= ENV.fetch("TEST_DATABASE_URL", nil) || ENV["DATABASE_URL"]&.sub(/cocopay_development/, "cocopay_test") %>

production:
  <<: *default
